# Generated by Django 3.2.4 on 2021-06-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='comment ya wazito'),
            preserve_default=False,
        ),
    ]
